services:
  love-wall:
    build: .
    image: lovewall:latest
    container_name: love-wall
    ports:
      - "8124:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
